---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos65
    driver:
      box: learningchef/centos65
      box_url: learninigchef/centos65

suites:
  - name: default
    run_list:

      - recipe[test1-motd::default]

    attributes:
