---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos65
    driver:
      box: learningchef/centos65
      box_url: learninigchef/centos65
      network:
        - [ "private_network", {ip: "192.168.38.35"}]

suites:
  - name: default
    run_list:

      - recipe[test1-motd::default]

    attributes:
